<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0 (Python 3.11.8 on darwin)" generated="2024-05-26T18:45:44.577301" rpa="false" schemaversion="5">
<suite id="s1" name="Test User Ddt" source="/Users/dierokreator/Programming/Interasys/PetStoreRobot140/__tests__/test_user_ddt.robot">
<test id="s1-t1" name="TC001" line="11">
<kw name="Create User DDT">
<msg time="2024-05-26T18:45:44.717226" level="FAIL">Variable '${id}' not found.</msg>
<arg>${id}</arg>
<arg>${username}</arg>
<arg>${firstName}</arg>
<arg>${lastName}</arg>
<arg>${email}</arg>
<arg>${password}</arg>
<arg>${phone}</arg>
<arg>${userStatus}</arg>
<status status="FAIL" start="2024-05-26T18:45:44.716494" elapsed="0.002861">Variable '${id}' not found.</status>
</kw>
<status status="FAIL" start="2024-05-26T18:45:44.714927" elapsed="0.004879">Variable '${id}' not found.</status>
</test>
<status status="FAIL" start="2024-05-26T18:45:44.581992" elapsed="0.138982"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test User Ddt">Test User Ddt</stat>
</suite>
</statistics>
<errors>
<msg time="2024-05-26T18:45:44.711333" level="ERROR">[ DataDriver ] Error in robot file:
  File "/Users/dierokreator/Programming/Interasys/PetStoreRobot140/__tests__/test_user_ddt.robot", line 0</msg>
<msg time="2024-05-26T18:45:44.711654" level="ERROR">In source file:
  File "../../fixtures/csv/user.csv", line 0</msg>
<msg time="2024-05-26T18:45:44.714638" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: FileNotFoundError: File attribute was not a full path. Tried to find /Users/dierokreator/Programming/Interasys/PetStoreRobot140/__tests__/../../fixtures/csv/user.csv but file does not exist.</msg>
</errors>
</robot>
